# Generated by Django 5.0 on 2024-01-04 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cryptocurrency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cryptocurrencey.cryptocurrency'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='mastercart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cryptocurrencey.mastercart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity_currency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity_mastercart',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cryptocurrency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='cryptocurrencey.cryptocurrency'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='mastercart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='cryptocurrencey.mastercart'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_mastercart',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_currency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_mastercart',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
