# Generated by Django 5.0 on 2024-01-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencey', '0002_alter_cartitem_cryptocurrency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mastercart',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10),
        ),
    ]
