# Generated by Django 5.0 on 2024-01-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencey', '0003_alter_cryptocurrency_price_alter_mastercart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mastercart',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
