# Generated by Django 5.0 on 2024-01-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencey', '0004_alter_cryptocurrency_price_alter_mastercart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcryptocurrency',
            name='status',
            field=models.CharField(choices=[('w', 'Waiting'), ('a', 'Approved'), ('c', 'Cancel')], default='w', max_length=50),
        ),
        migrations.AlterField(
            model_name='commentmastercart',
            name='status',
            field=models.CharField(choices=[('w', 'Waiting'), ('a', 'Approved'), ('c', 'Cancel')], default='w', max_length=50),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='status',
            field=models.CharField(choices=[('w', 'Waiting'), ('a', 'Approved'), ('n', 'NOT Approved')], default='w', max_length=255),
        ),
    ]
