# Generated by Django 5.0 on 2024-01-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=1, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=255, verbose_name='full_name'),
            preserve_default=False,
        ),
    ]
